import localFont from "next/font/local";
import "./globals.css";
import Nav from "@/components/nav";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script src="https://kit.fontawesome.com/9c453524b4.js" async crossorigin="anonymous"></script>
      </head>
      <body
        id="body" className={`${geistSans.variable} ${geistMono.variable} antialiased dark:bg-black bg-slate-50 flex flex-col h-svh`}
      >
        <Nav />
        {children}
      </body>
    </html>
  );
}
